### PR TITLE
Fix CI for Chum GUI's special requirements

### PR DESCRIPTION
**Pull request by Olf0**

### CODE REVIEW

**Comment by rinigus** [comment]
Apart from not finishing the build, LGTM. Good luck!

**Comment by rinigus** [comment]
PS: For me, it is always lengthy process to get CI to work as you need. Bit it works out, eventually.

**Comment by Olf0** [comment]
Remaining open point: https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/140#issuecomment-1400954367

**Comment by Olf0** [comment]
Closing, because [`mb2`](https://github.com/sailfishos/sdk-setup/blob/master/sdk-setup/src/mb2) seems to be severely broken.

I also [documented my horrible experiences with `mb2`](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/140#issuecomment-1403838911).

**Comment by Olf0** [comment]
@rinigus, I would like to "archive" this branch (i.e., setting it read-only) for documenting almost two nights of work.  This can be achieved by setting *Settings → Branches → Branch protection rules → New → Branch name pattern `fix-ci`, plus enable `Lock branch` and `Do not allow bypassing the above settings`*.

I cannot set this, so either provide me with the access privilege to the repo settings or just set it.

In also would like to see in *Settings → General → Automatically delete head branches* enabled as an organisation-wide setting (i.e., for all repos), because it is quite convenient to have a branch automatically deleted after it has been merged (can be undone for a while): Does that need discussion?

Additionally I would like to suggest to enable *Settings → General → Always suggest updating pull request branches* for all repos: AFAIU it only has an effect in GitHub's web-frontend and can be convenient at times.  I do not remember, if this can be enabled as an organisation-wide setting, surprisingly I can already enable it on repository-level (in contrast to the other settings mentioned).

**Comment by rinigus** [comment]
I have made you and Admin in this repository. Will look now on org settings

**Comment by Olf0** [comment]
> I have made you and Admin in this repository. Will look now on org settings

So did I: Sorry, for these settings there seems to be no org-wide default, which is applied to new or all existing repositories (I saw either of both for a few other settings).

I set them for this repo as mentioned above, thanks to the admin access you granted me.

For Patchmanager we imposed "Require a pull request before merging" in the branch protection rule for "main" also for Admins.  I did not switch it on for Admins yet, but would like to: Lastly it enforces all changesets to have undergone a CI run.  Even it a pull request is merged without waiting for the CI run to finish, one can look at its result later (< 90 days).

**Pull request closed without merging**
