### PR TITLE
Allow to specify description as URL pointing to MarkDown

### LINKED ISSUE #73: Add an url to a readme (markdown) to the package
It would be nice to add an url to a readme (markdown) to the package:

```yaml
name: Dummy App
type: desktop-application # not sure we need that
categories:
- Media
custom:
- repo: https://github.com//johndoe/harbour-dummy-app/
icon: https://raw.githubusercontent.com//johndoe/harbour-dummy-app/master/harbour-dummy-app.svg
screenshots:
- https://github.com/johndoe/harbour-dummy-app/raw/master/metadata/screenshots/screenshot1.png
- https://github.com//johndoe/harbour-dummy-app/raw/master/metadata/screenshots/screenshot2.png
- https://github.com//johndoe/harbour-dummy-app/raw/master/metadata/screenshots/screenshot3.png
url:
- donation: https://www.paypal.me/johndoe
- readme: https://github.com/johndoe/harbour-dummy-app/raw/master/README.md
```
This could be rendered in Chum GUI instead of the description if present.

_Originally posted by @black-sheep-dev in https://github.com/sailfishos-chum/main/issues/29#issuecomment-1008158448_

### PR DESCRIPTION
**Pull request by rinigus**
Fixes #73 

This PR adds `Custom/DescriptionMD` that is expected to point to a MarkDown file via URL. If specified, description is pulled from that URL and rendered instead of description given in SPEC. Until remote description is pulled, SPEC description is shown.

PR is based on example code by @black-sheep-dev further adjusted for our case.

Example package using this approach: bash-git-prompt in chum:testing. See SPEC: https://build.sailfishos.org/package/view_file/sailfishos:chum:testing/bash-git-prompt/bash-git-prompt.spec?expand=1

Please review.

### CODE REVIEW

**Comment by piggz** [comment]
This will need a corresponding PR to main right?

**Comment by rinigus** [comment]
Yes, that's right to document the addition in Metadata format

**Comment by rinigus** [comment]
@piggz - I suggest that metadata documentation PR will be after we have gone through this PR. unless this is in, there is no point in changing docs

**Comment by piggz** [comment]
Tested and works, though, I found some of the text to be a bit on the large side, what do you think?

**Comment by rinigus** [comment]
it is towards large, indeed. Already tried to reduce it, but probably more is needed. will try tonight (hopefully)

**Comment by rinigus** [comment]
@piggz: I have reduced further the headers. Its still not perfect, but maybe good enough for the first version. If someone wants to adjust the style, it can be done later separately. Also not sure it is the best README we can render in Chum GUI.

Please review

**Pull request merged**
