### PR TITLE
Update sailfishos-chum-gui-sk.ts

### PR DESCRIPTION
**Pull request by okruhliak**
Added slovak translation

### CODE REVIEW

**Comment by rinigus** [comment]
Thank you

**Comment by Olf0** [comment]
@okruhliak, I moved the strings translation for the SailfishOS:Chum GUI application to Transifex: https://www.transifex.com/olf/sailfishos-chum-gui/dashboard/

I would appreciate very much, if you apply for the role as "Coordinator" for Slovak (`sk`) there.

**Comment by okruhliak** [comment]
@Olf0 , OK, thanks for the info. I can be a coordinator for Slovak. In Transifex, my nickname is "holask".

**Comment by Olf0** [comment]
Done, thank you!

**Pull request merged**
