### PR TITLE
Check if there is a description before processing it, fixes #264

### LINKED ISSUE #264: [Bug] Crash when processing packages without description
As reported in https://forum.sailfishos.org/t/announcing-sailfishos-chum-gui-0-3/9839/98

Caused by https://build.sailfishos.org/package/view_file/sailfishos:chum:testing/harbour-bibletime/_service:tar_git:harbour-bibletime.spec?expand=1

Fix incoming

### PR DESCRIPTION
**Pull request by rinigus**
Please review.

/cc @piggz

### CODE REVIEW

**Comment by rinigus** [comment]
OK, as the change is trivial - I am going to merge this.

**Comment by rinigus** [comment]
@Olf0 - would you mind to make a release with this?

**Comment by Olf0** [comment]
> @Olf0 - would you mind to make a release with this?

Usually not, but I caught the classic flu (influenza), which still keeps me busy: Thus I am glad that someone else did (presumably you).

**Comment by rinigus** [comment]
Yes, I made the release. And it looks that you have already arranged everything for the next one. Thank you and get well!

**Pull request merged**
