### PR TITLE
Show more information regarding package in a list

### LINKED ISSUE #26: Show more information in the package list
As we have several attributes exposed via `ChumPackagesModel` (see current state at https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/src/chumpackagesmodel.cpp#L42), lets show it in the list as well. Probably a listing implementation as in Storeman (one column list as opposed to Jolla's two-column approach) would work nicely. 

Looking at the properties, we should expose "packageUpdateAvailable" as well.

### PR DESCRIPTION
**Pull request by rinigus**
This adds information regarding a package in the list. Please review.

Fixes #26

### CODE REVIEW

**Comment by piggz** [comment]
Great improvement
I wonder if you could align the stars so that they line up with 1) some have 1-9, other s have >100, 2) some packages are installed.

**Comment by rinigus** [comment]
Yes, we can improve the alignment. Right now we have * ranges from 0-10700 (Brotli) - those you see when you look at all packages, not just apps.

We can put installed status on the top of stars. That way, stars alignment will not be disturbed by install (or update) status.

As for stars not being aligned, I can swap the order and put number in the front of a star and not star-number as it is now. 

What do you think? Should I try - we may not like it in the end, but I guess it is OK to try like that

**Comment by rinigus** [comment]
@piggz: yes, it seems to be better

See attached

Screenshot_20211230_001

**Comment by piggz** [comment]
LGTM, you want to merge like this?

**Pull request merged**
