### PR TITLE
Color links in theme colors.

### PR DESCRIPTION
**Pull request by nephros**
See #186

### CODE REVIEW

**Comment by rinigus** [comment]
I suggest to merge it and see how it goes. Don't have time to test it, but it can be done via Chum testing build. @piggz, @Olf0 - your take on it?

**Comment by piggz** [comment]
Its terrible, i love it :D

**Comment by rinigus** [comment]
Tested with the build at Chum:Testing. @Olf0, would you mind making a new release with it? Then we can push it to Chum proper.

**Comment by Olf0** [comment]
Will do, when time permits.

**Pull request merged**
