### PR TITLE
German locale overhaul

### PR DESCRIPTION
**Pull request by spodermenpls**
I harmonized the translations with the source strings (the oldsource strings are a massive nuisance for this..) and smoothed some phrasings and two or three typos.

Three quick notes: 
- in German, nouns are connected by hyphens (for readability, I deviated at "SailfishOS:Chum Community-Repository" and "SailfishOS:Chum Testing-Repository" slightly)
- in German, the plural of the borrowed word "Repository" is "Repositorys" (https://www.duden.de/rechtschreibung/Repository)
- "Issue-Tracker"/"Fehlerbericht": I think it's better to just borrow the term from English as a whole, also since not every "Issue" revolves around an actual bug/"Fehler"

### CODE REVIEW

**Review by Olf0 — COMMENTED** [review]
Thank you very much for your contribution, which is a nice improvement compared with the original contribution via PR #125.

Addressing your three points:
1. Thank you for taking the freedom to deviate from the rule in order to avoid long chains of hyphenated nouns.  Nitpick: I believe the rule is, "a hyphen shall be used, when concatenating nouns from a foreign language or nouns from different languages".
2. Oh, this looks so awful and wrong to me, plus Duden is just a publishing house, which does not have a normative status like the Académie Française.  There are counterexamples, i.e., foreign words for which their original plural inflection is used.  Do you have a second source?  dwds.de (which I trust more) does not list "Repository" at all, which is another reason why I think it should rather stay unaltered, including its plural form.
   IMO the underlying, real issue is, that nobody seems to have provided a proper German expression for "Repository", which does not sound artificial.
3. While I concur with your argument, I see perceive this as a significant usability hurdle, which is detrimental to the very purpose of translated strings: To make the software accessible for users who do not understand English. This does not apply to "Repository", because those who do not understand the term will also be unable to use a repository. But for "issue tracker" a translation is crucial. Do not mind to deviate far from the original term; you may use a description etc. FYI: The issue tracker currently hosts three templates, for bug reports, help requests and feature suggestions.

**Comment by spodermenpls** [comment]
Good catch on the accent circonflex ontop of the "e", must've hit the key underneath Escape once without noticing.
The article though is not indicating a plural, the source string is using the singular, I used the wrong article though, it's supposed to be "das" instead of "die".

So the correct string is this:
"Die SailfishOS:Chum-GUI-App konnte das SailfishOS:Chum-Repository nicht verwalten! Vielleicht hast du mehrere SailfishOS:Chum-Repositorys für SSU definiert oder ein SailfishOS:Chum-Repository deaktiviert. (...)"

**Comment by Olf0** [comment]
Sorry, I kept on editing my comment.  I have to stop, because I feel as if I have contracted a cold or flu: By tomorrow I should know what it is.

**Comment by spodermenpls** [comment]
> Thank you for taking the freedom to deviate from the rule in order to avoid long chains of hyphenated nouns.  Nitpick: I > believe the rule is, "a hyphen shall be used, when concatenating nouns from a foreign language or nouns from different languages".

Yes, the emphasis is rather on "nouns are _connected_" (in opposite of the English practice, which seems to confuse many translators) than "connected by _hyphens_", since you would just splice the words together, if using "normal" German nouns, without anything in between.

> Oh, this looks so awful and wrong to me, plus Duden is just a publishing house, which does not have a normative status like the Académie Française.  There are counterexamples, i.e., foreign words for which their original plural inflection is used.  Do you have a second source?  dwds.de (which I trust more) does not list "Repository" at all, which is another reason why I think it should rather stay unaltered, including its plural form.

Yes, I do have more sources/examples:
https://www.ibm.com/docs/de/installation-manager/1.8.5?topic=files-repositories
https://docs.github.com/de/repositories/creating-and-managing-repositories/about-repositories (even Github uses this!)
https://docs.oracle.com/cloud/help/de/content-cloud/CECDA/GUID-33E7F38E-E5F9-4D32-8077-A47876096FAE.htm
I know it sounds/reads a bit weird, if you're used to using it in the English context, but this seems to be the de-facto standard, if you want to have an actual _German translation_.
And before I decided to go with "Repositorys", I found a good summary in regards to plural inflections of borrowed words from English and French (even if not straight from the official regulating body): https://languagetool.org/insights/de/beitrag/plural-anglizismen-gallizismen/

> While I concur with your argument, I see perceive this as a significant usability hurdle, which is detrimental to the very purpose of translated strings: To make the software accessible for users who do not understand English. This does not apply to "Repository", because those who do not understand the term will also be unable to use a repository. But for "issue tracker" a translation is crucial. Do not mind to deviate far from the original term; you may use a description etc. FYI: The issue tracker currently hosts three templates, for bug reports, help requests and feature suggestions.

I don't agree on this, using "Issue" in the realm of this use case as a borrowed term is equivalent to the use of "Repository". Even Codeberg, which is developed and hosted by Germans and has an otherwise localized German UI, is borrowing the term "Issue" (among others) as a concise way of labeling this category: https://codeberg.org/nobody/LocalCDN/issues . I also don't fully agree on "accessibility for people who don't understand English". If you don't understand English (or more so in this case, commonly used "technical terms") _at all_, do you really think a user would install "SailfishOS:Chum", let alone use Sailfish in the first place, whose documentations are mostly (and exclusively) in English anyway? I think expecting a little bit of English prowess, especially when there's just no way of replicating native German words that are as concise and handy as the English expressions "Issue" and "Tracker".

**Comment by Olf0** [comment]
> First of all, gute Besserung!

Thank you, unfortunately this took a while, as I contracted CoViD for the first time.  Hence the late reply.

> [...]
> 
> > Oh, this looks so awful and wrong to me, plus Duden is just a publishing house, which does not have a normative status like the Académie Française.  There are counterexamples, i.e., foreign words for which their original plural inflection is used.  Do you have a second source?  dwds.de (which I trust more) does not list "Repository" at all, which is another reason why I think it should rather stay unaltered, including its plural form.
> 
> Yes, I do have more sources/examples: https://www.ibm.com/docs/de/installation-manager/1.8.5?topic=files-repositories https://docs.github.com/de/repositories/creating-and-managing-repositories/about-repositories (even Github uses this!) https://docs.oracle.com/cloud/help/de/content-cloud/CECDA/GUID-33E7F38E-E5F9-4D32-8077-A47876096FAE.htm I know it sounds/reads a bit weird, if you're used to using it in the English context, but this seems to be the de-facto standard, if you want to have an actual _German translation_. And before I decided to go with "Repositorys", I found a good summary in regards to plural inflections of borrowed words from English and French (even if not straight from the official regulating body): https://languagetool.org/insights/de/beitrag/plural-anglizismen-gallizismen/

These examples are fine, but even more so your last link.  Thanks!

> > While I concur with your argument, I see perceive this as a significant usability hurdle, which is detrimental to the very purpose of translated strings: To make the software accessible for users who do not understand English. This does not apply to "Repository", because those who do not understand the term will also be unable to use a repository. But for "issue tracker" a translation is crucial. Do not mind to deviate far from the original term; you may use a description etc. FYI: The issue tracker currently hosts three templates, for bug reports, help requests and feature suggestions.
> 
> I don't agree on this, using "Issue" in the realm of this use case as a borrowed term is equivalent to the use of "Repository". Even Codeberg, which is developed and hosted by Germans and has an otherwise localized German UI, is borrowing the term "Issue" (among others) as a concise way of labeling this category: https://codeberg.org/nobody/LocalCDN/issues . 

This is fine, because these are tools for developers and "the language of IT is English" (nowadays) as a matter of fact (A.E., unfortunately).  In contrast to that, software shall be easy to use for simple users, otherwise all l10n / i18n efforts are just an academic exercise: I.e., we might as well leave it all untranslated.  I am regularly surprised to see at FSO how many SFOS users lack any UNIX knowledge and barely capable of expressing themselves in English; mind that this perception is created by people who are willing to participate in an English language forum.

> I also don't fully agree on "accessibility for people who don't understand English". If you don't understand English (or more so in this case, commonly used "technical terms") _at all_, do you really think a user would install "SailfishOS:Chum", let alone use Sailfish in the first place, whose documentations are mostly (and exclusively) in English anyway? 

Very simple: Have somebody else around who does that.  A friend, spouse etc.  A couple of people at FSO mention that they do that for others.  I did that twice for people lacking the technical know-how and regret that I did, because despite clearly stating that I will only help across the perceived (by them) "installation hurdle", they both continuously refused to use FSO or read documentation.

> I think expecting a little bit of English prowess, 

Oh, so you do see this as a purely academic exercise?  Because with this expectation in mind what we are dealing with and discussing here is superfluous.

> especially when there's just no way of replicating native German words that are as concise and handy as the English expressions "Issue" and "Tracker", is okay.

"Issue" is not concise at all, rather the opposite: an extremely generic term with multiple, quite different meanings.  It just allows for terse phrases, which also are very broad and/or ambiguous.

> Also, even if the term may confuse some few people in your scenario, a click on it and seeing the actual purpose of this category should be sufficiently self-explanatory in the end.

You made me consider what I originally suggested for the translation: To pan out which kind of "issues" might be addressed: bug reports, feature suggestions and help requests.  It would be helpful for me to read a phrase, which covers these, preferably with a suggestion for a new source string.

**Comment by Olf0** [comment]
Want to release now, will alter source and target string after that.

Current working notion for a translation of "Bug reports, feature suggestions and help requests" is "Fehlerberichte, Verbesserungsvorschläge und Hilfeanfragen".

**Comment by spodermenpls** [comment]
Sorry for the delay, I had most of my response done in my mind already, but was postponing publishing it due to being occupied with other stuff..

> This is fine, because these are tools for developers and "the language of IT is English" (nowadays) as a matter of fact (A.E., unfortunately). In contrast to that, software shall be easy to use for simple users, otherwise all l10n / i18n efforts are just an academic exercise: I.e., we might as well leave it all untranslated. I am regularly surprised to see at FSO how many SFOS users lack any UNIX knowledge and barely capable of expressing themselves in English; mind that this perception is created by people who are willing to participate in an English language forum.

That's not true at all, platforms like Github or Codeberg are meant (at least in the context of open-source projects) to be used for regular, non-techsavvy (even DAU) users to report bugs, problems and ask questions. Or short: Report issues. 😄

> Oh, so you do see this as a purely academic exercise? Because with this expectation in mind what we are dealing with and discussing here is superfluous.

You are throwing the baby out with the bath water, translating within limited space always is a compromise between accuracy, conciseness and understandability. "Issue" might indeed be an edge-case, but even "Tracker" has creeped into colloquial German language already ("Kalorientracker", "Fitnesstracker"), that's the level of "a little bit of English prowess" I am talking about, not "why bother with the nitty-gritty of translation, Sailfish users are English savants anyway).

> > especially when there's just no way of replicating native German words that are as concise and handy as the English expressions "Issue" and "Tracker", is okay.
> 
> "Issue" is not concise at all, rather the opposite: an extremely generic term with multiple, quite different meanings. It just allows for terse phrases, which also are very broad and/or ambiguous.

That's your opinion, but I won't die on that hill. If you want to replace it with the longwinded, but 100 % home-grown "Fehlerberichte, Verbesserungsvorschläge und Hilfeanfragen", feel free to do it, I have no better idea than that either.

**Comment by spodermenpls** [comment]
@Olf0 Alright, only after seeing the changes in actual application, I can see the whole picture now. I was convinced for some reason "Issue tracker" would actually be in place of "Probleme", but it's just the entry in the pulley menu, that contains the URL to the projects' pages. I saw your tweak of just extending "Issue tracker" with "... for bug reports, feature suggestions and help requests" may very well be the most elegant solution.

**Comment by Olf0** [comment]
… this is what I assumed.

BTW, all these source strings are "home grown", i.e., authored by me; their original state was what you can still see for all source strings as `<old source>` (except for "Issue tracker" since PR #159) in the TS files.  As you can derive from that, I always "feel free to do" as I deem right, after sufficient consideration and taking all criticism into account (which by no means equals to obeying it); this is why I love discussions and criticism, but am also quite used to people become angry if I ultimately do not follow their suggestions.

Plus one should always look at strings in their specific context.  Here specifically you might have realised that "translating within limited space" is not at all true, rather the contrary: a longer, more easily visible string constitutes an improvement.

**Comment by spodermenpls** [comment]
@Olf0 I meant by "home-grown" in this instance "German, without relying on anglicisms", not authorship. The position was self-explanatory in this case, but doing translations for a bunch of projects by now taught me to, when in doubt, to rather take a swing and correct it if necessary after seeing it actually implemented (needed or unneeded details like spaces, hyphens and such are sometimes impossible to foresee - not in this case obviosuly), than to dwell on it for hours, to get a perfect result on the first try.

**Comment by Olf0** [comment]
> @Olf0 I meant by "home-grown" in this instance "German, without relying on anglicisms", not authorship.

Oh, well, avoiding metaphors (and colloquialisms) due to them implicitly being ambiguous (to a varying extent).  That was very easy to misunderstand and absolutely orthogonal to the way I think: Can I easily construct a very similar phrase in German (or vice versa: in English) is my principal concept.

> The position of these strings was (or should've been, for me..) self-explanatory in this case, but doing translations for a bunch of projects by now taught me to, when in doubt, to rather take a swing and correct it if necessary after seeing it actually implemented (needed or unneeded details like spaces, hyphens and such are sometimes impossible to foresee - not in this case obviously), than to dwell on it for hours, to get a perfect result on the first try.

Generally I do concur, but this already was the third round; PR #125 initially provided the quick & dirty (= quite crude) translation with lots of very rough edges.  I enhanced PR #125 significantly, but my time and capabilities are limited; as I am the only one who takes care about the source strings, I want to limit my work on translations to quality assurance.

Hence I do appreciate that you paid attention to details, did answer my checks & balances questions exhaustingly and improved a mediocre translation to become excellent.  

BTW, as you are quite capable in both, German and English (and maybe more languages) and seem to have fun performing string translations for Free Software: If a source string appears to be strange or simply wrong, to rectify that first after checking the context in the software (this can often be achieved even without running the software, just by looking at its source code).  I mention that, because most translators do stubbornly translate obvious nonsense (well, apparently not sufficiently obvious to them), which is not really helpful, because it increases the work to correct that in multiple languages, later.

HTH & Cheers!

**Comment by Olf0** [comment]
@spodermenpls, I moved the strings translation for the SailfishOS:Chum GUI application to Transifex: https://www.transifex.com/olf/sailfishos-chum-gui/dashboard/

I would appreciate very much, if you apply for the role as "Coordinator" for German (`de`) there.

**Comment by spodermenpls** [comment]
@Olf0 My hunch about your "Issue-Tracker" oneliner being in a space-constrained environment wasn't that far off after all:
Bildschirmfoto_20230321_001
This is how it looks on my XA2. 😄

**Comment by Olf0** [comment]
Thank you for checking.  Oops, it should soft-wrap (at least that is how I envisioned it), as the lines below do.  Will check, and preferably fix or revert.

**Pull request merged**
