### PR TITLE
Change DNS-name sailfishos-chum-gui-sk.ts

### PR DESCRIPTION
**Pull request by okruhliak**
Change SFOS-OBS DNS-name

### CODE REVIEW

**Review by Olf0 — COMMENTED** [review]
LGTM

**Review by Olf0 — APPROVED** [review]

**Comment by okruhliak** [comment]
I have version 0.5.4 installed on Xperia 10 III, according to the release description, it should also include Slovak localization, but the application is in English even though my device is entirely in Slovak. Should I uninstall the app and reinstall it for the language change to take effect, or...?

**Comment by Olf0** [comment]
Thank you for the hint, I found that `sailfishos-chum-gui-sk.ts` was missing in [translations/CMakeLists.txt](https://github.com/sailfishos-chum/sailfishos-chum-gui/blob/main/translations/CMakeLists.txt).

Fixed by dea15a7

Sorry, will be in next release.

**Comment by Olf0** [comment]
@okruhliak, please check [v0.5.5](https://github.com/sailfishos-chum/sailfishos-chum-gui/releases/tag/0.5.5) (also available at [SailfishOS:Chum:Testing](https://build.merproject.org/package/show/sailfishos:chum:testing/sailfishos-chum-gui)), which should finally use your Slovak translation.  Sorry, I now realised that it was integrated, but not activated since [your PR \#123](https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/123) in April 2022.

**Comment by okruhliak** [comment]
Yes, I confirm, Slovak works in the main version and in the test version, thank you! :+1:

**Pull request merged**
