### PR TITLE
Packages: show installed; allow to uninstall; sync info with changes

### PR DESCRIPTION
**Pull request by rinigus**
This is on top of #31 - should be reviewed after that.

Fixes: #22 #23 #24 #36 #37

On top of these fixes, it has slightly revised packagepage that should use available space better (calculates available area to show description in shrunk form) and shifts categories/installation status next to stars/forks info (through dedicated item appsummary.qml).

### CODE REVIEW

**Comment by rinigus** [comment]
Allows also to list just applications (desktop or console) in the lists. For applications, shows its type in the summary.

**Comment by rinigus** [comment]
Right now there is a bug with listing updates. There is an error while composing a string on display of updates page, one of the subtitles is wrong, should use arg instead of just an additional argument to translated string. Will fix probably tomorrow

**Comment by rinigus** [comment]
The bug mentioned above is fixed in the commits pushed to this branch.

**Comment by piggz** [comment]
When uninstalling a package, there should be a notification just like when installed.

**Comment by rinigus** [comment]
Indeed. I will look into notifications

**Comment by rinigus** [comment]
@piggz: notifications have been adjusted and show up on uninstall. They also show package version as it used to be before.

**Pull request merged**
