### PR TITLE
Metadata: parse new names

### PR DESCRIPTION
**Pull request by nephros**
Implements parsing new tags

 - PackageName  || Title
 - PackagerName || PackagedBy
 - Icon         || PackageIcon
 - Url          || Links

See https://github.com/sailfishos-chum/main/issues/100

As the implementor I have taken the liberty of supporting PackagedBy as well, because I like it.

### CODE REVIEW

**Review by Olf0 — APPROVED** [review]
LGTM

Thank you very much, will overhaul [the section "field descriptions" of Metadata.md](https://github.com/sailfishos-chum/main/blob/main/Metadata.md#field-descriptions) in the upcoming days.

**Comment by rinigus** [comment]
Thank you very much, LGTM

**Comment by Olf0** [comment]
@nephros, unfortunately this change fails to compile: 
[chum-gui-0.6.0_compiling-fails.txt](https://github.com/sailfishos-chum/sailfishos-chum-gui/files/11133306/chum-gui-0.6.0_compiling-fails.txt)

Can you please take a look at it.

**Comment by Olf0** [comment]
> Damn, missing closing bracket.

… which I failed to see (despite being trivial) due to being overly tired when I detected that building fails.

> Sorry about that.

Never mind.  It uncovered another issues: The CI runs at GitHub [show success](https://github.com/sailfishos-chum/sailfishos-chum-gui/actions/runs/4589561618), even though [compiling fails](https://github.com/sailfishos-chum/sailfishos-chum-gui/actions/runs/4589561618/jobs/8104537420#step:3:185)!  I have to [improve the workflow definition(s)](https://www.softwaretester.blog/detecting-github-workflow-job-run-status-changes).

> Fixes coming up!

Thank you for PR #185.  Merged and [compiling](https://github.com/sailfishos-chum/sailfishos-chum-gui/actions/runs/4594057570), as expected.

**Pull request merged**
