### PR TITLE
SettingsPage & chum.cpp: Concise wording

### PR DESCRIPTION
**Pull request by Olf0**

### CODE REVIEW

**Comment by Olf0** [comment]
@rinigus, I am unable to find the location of the transient messages, which are displayed while the repository is refreshed:
1. XXXX (appears too briefly for me to read it)
2. Refreshing Chum repository
3. Get list of packages
4. Get package details
5. YYYY (appears too briefly for me to read it)
6. Check for updates

Can you provide me with a pointer to the corresponding source file, please.

I would like to unify the wording here to (at least) always use the present tense: Currently it is a mix of continuous forms ("refresh**ing**) and present tense ("check", "get").  While the continuous form would be technically correct, it is longer and does not add any real information.
If you prefer to always use the continuous form, please let me know, and I will unify the messages to that tense.  I don't really mind, but want it to be consistent.
If I only knew were these messages are.

**Comment by rinigus** [comment]
Few messages are in `src`:

```
grep -r "//% " src
```

**Comment by dikonov** [comment]
Continuous forms are more friendly for the translators. They make our work a bit less prone to the typical error of mixing up a menu command label "Do X" and an information message that might appear afterwards "Doing X". 
* It is often impossible to see the actual result before the maintainer builds and uploads an updated package, when all your errors get distributed to the users.

**Comment by Olf0** [comment]
> Few messages are in `src`:
> 
> ```
> grep -r "//% " src
> ```

Well, I did not have the source (repo) locally. 
O.K., all are in `chum.cpp`, except for two in `chumpackage.cpp` ("Library" and "Development").

@dikonov commented:
> Continuous forms are more friendly to the translators. They make our work a bit less prone to the typical error of mixing up a menu command label "Do X" and an information message that might appear afterwards "Doing X".

* Well this not really the case here, these actions are carried out mostly automatically, hence there is no corresponding "menu command" "Do X" (well, there is a single one), which triggers the messages "Doing X" (ten, of which nine currently say "Do X").
* Currently a single out of ten messages is in the continuous form, all others are in the present tense, thus the obvious way to consolidate them is to use the present tense.
* Also note that the messages shall not become too long, the continuous form usually adds the three characters "ing".
* Still, the continuous form is technically correct and hence I like it, when I put all practical consideration aside.  But OTOH these practical considerations are relevant.

@piggz and @rinigus do you have an opinion to share WRT this?

**Comment by rinigus** [comment]
When I add those messages, I was trying to be correct in the sense of the form. I expect it would be handy when getting bug requests like "GUI got stuck in ...". Other than that, not much to add

**Comment by Olf0** [comment]
Thus was a lot of C++ code for me to understand roughly, in order to enhance the comment and output strings correctly.  I hope to have achieved that, please check thoroughly, because at some places I was not sure what the original strings meant and what exactly the code does.
I also hope that the output strings are subjected to line-wrapping; if not, we will have to see in practice if they fit and may have to shorten some.

**Comment by rinigus** [comment]
Thank you very much! In addition to user-visible messages, we also have code comments gone through! Merging

**Comment by rinigus** [comment]
In chum:testing, the build has been bumped to include the corrected strings. Should be ready in few minutes

**Comment by Olf0** [comment]
> Thank you very much! In addition to user-visible messages, we also have code comments gone through! Merging

You are welcome.  Because some of the output strings were quite ambiguous for me, I had to read the comments thoroughly and partially had similar trouble with them.  So I tried to read the code (which I am bad at, if it is C++ or JavaScript), and enhanced comments and output strings to my understanding.  As this is a rather vague process, I asked you to do a thorough quality assurance of my changes, because you understand way better what the code really does.

> In chum:testing, the build has been bumped to include the corrected strings. Should be ready in few minutes

Thank you that was very helpful to check and see that I missed two strings.  Now I remember that I wanted to return to these two later, but forgot to.  These are addressed in PR #112.

**Pull request merged**
